version: '3.9'

services:
    php-fpm:
        build:
            context: .
            target: threeci-php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html/
            - ./.docker/php/logs/xdebug:/var/log/xdebug/
        networks:
            - threeci_network

    nginx:
        build:
            context: .
            target: threeci-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html/
            - ./.docker/nginx/logs:/var/log/nginx/
        networks:
            - threeci_network

volumes:
    db:
        driver: local

networks:
    threeci_network:
        driver: bridge