name: Check security

on:
    push:
    pull_request:

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:

    security:
        name: Check security
        runs-on: Ubuntu-20.04

        strategy:
            matrix:
                php: ['8.1', '8.2']
            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: "zip xml mbstring intl apcu opcache"
                  ini-values: date.timezone=UTC,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1
                  php-version: "${{ matrix.php }}"
                  tools: pecl

            - name: Install Symfony cli
              run: |
                  curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash
                  sudo apt install symfony-cli

            - name: Install dependencies
              run: |
                  composer install

            - name: Check security
              run: symfony check:security